### ISSUE TITLE
Feature Request: `matchExact` for `Jason.string` method

### ISSUE THREAD

**Issue by MierenManz** [sno2/jason#1]
It would be nice to have `matchExact` as a key for `Jason.string` in addition to `startsWith` and `endsWith`

```ts
Jason.string({
  startsWith: "my string",
  endsWith: "my string",
});
```

**Comment by sno2** [comment]
I agree with the need to check for exact equality.  However, I don't really like the pitfalls that other libraries have fallen into with have many properties that override each other and change behavior of each other.  Therefore, how do you think a generic `jason.matches((value: T) => boolean)` would still allow for good type generation as we could infer that value as `T` through genetics.  The callback would return whether the value is valid or not and we can create good error messages with that.

**Comment by MierenManz** [comment]
So we would replace `Jason.string` with `Jason.matches((val) => val === "exact match")` for exact matches and `Jason.matches((val) => val.startWith("start"))`  for startsWith and remove those properties from string etc in favor of this? Or am I seeing that wrong?

**Comment by sno2** [comment]
> 
> 
> So we would replace `Jason.string` with `Jason.matches((val) => val === "exact match")` for exact matches and `Jason.matches((val) => val.startWith("start"))` for startsWith and remove those properties from string etc in favor of this? Or am I seeing that wrong?

Sorry for late response, had been working on school and another thing.  Basically, I just want to not add a ton of bloat properties into the `jason.string` composable that can override each other.  Therefore, I think it'd be best to add exactly what you outlined in your PR, thanks.
